print("Senior Project Developer Profile")
print()
print("Name: Caleb Nathaniel Orr")
print("Major: Computer Science")
print("Technology Interest: Artificial Intelligence and Cybersecurity")
print("Skill Goal: Data Science")
